<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_ArmCart" Id="{acf69b98-a94c-45d6-930a-e719a9a02026}" SpecialFunc="None">
    <Declaration><![CDATA[// Brief: Master Arm Cart Control
FUNCTION_BLOCK PUBLIC FB_ArmCart EXTENDS FB_MasterArmCtrlBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_ArmCart">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>