<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_StateCtrlCart" Id="{acf69b98-a94c-45d6-930a-e719a9a02026}" SpecialFunc="None">
    <Declaration><![CDATA[// Brief: Master Arm Cart Control
FUNCTION_BLOCK PUBLIC FB_StateCtrlCart EXTENDS FB_MasterArmCtrlBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="init" Id="{1dc1fdc9-dd5b-4a4c-998e-6b8ceff7fdd6}">
      <Declaration><![CDATA[METHOD PUBLIC init : BOOL
VAR_IN_OUT CONSTANT
	i_masterArm	:FB_MasterArm;
END_VAR
VAR_IN_OUT 
	r_masterArmCtrlCmd :ST_ArmCtrlCmds;
END_VAR

]]></Declaration>
      <Implementation>
        <ST><![CDATA[// check if to hold the command joint position unchanged
m_holdLastCmds := checkToHoldLastCmds(i_masterArm);

// init
SUPER^.Init(i_masterArm,r_masterArmCtrlCmd);

]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_StateCtrlCart">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_StateCtrlCart.init">
      <LineId Id="69" Count="2" />
      <LineId Id="68" Count="0" />
      <LineId Id="57" Count="1" />
      <LineId Id="12" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>