<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_StateCtrlReady" Id="{b4863c0c-c549-4967-ab29-6a1152ef3cd8}" SpecialFunc="None">
    <Declaration><![CDATA[// Brief: Master Arm Ready for Master Slave Control
FUNCTION_BLOCK PUBLIC FB_StateCtrlReady EXTENDS FB_MasterArmCtrlBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	
cmdPos, curPos :Vec7d;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="init" Id="{2537cbc9-bbc0-4d20-a9bf-3a888748c955}">
      <Declaration><![CDATA[METHOD PUBLIC init : BOOL
VAR_IN_OUT CONSTANT
	i_masterArm	:FB_MasterArm;
END_VAR
VAR_IN_OUT 
	r_masterArmCtrlCmd :ST_ArmCtrlCmds;
END_VAR

VAR
	j:INT;
	maxJntErr:LREAL;
	jntCtrlErr:Vec7d;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[// check if to hold the command joint position unchanged
m_holdLastCmds := checkToHoldLastCmds(i_masterArm);

// init
SUPER^.Init(i_masterArm,r_masterArmCtrlCmd);
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_StateCtrlReady">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_StateCtrlReady.init">
      <LineId Id="72" Count="1" />
      <LineId Id="93" Count="0" />
      <LineId Id="75" Count="1" />
      <LineId Id="12" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>