<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="normVec7" Id="{d7024f30-d686-4cf4-a982-22f9800ecd88}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION normVec7 : LREAL
VAR_IN_OUT CONSTANT
	vec7 :Vec7d;
END_VAR
VAR
	i:INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[normVec7:=SQRT(vec7[1]*vec7[1]+vec7[2]*vec7[2]+vec7[3]*vec7[3] + 
				vec7[4]*vec7[4]+vec7[5]*vec7[5]+vec7[6]*vec7[6]+vec7[7]*vec7[7]);]]></ST>
    </Implementation>
    <LineIds Name="normVec7">
      <LineId Id="7" Count="0" />
      <LineId Id="18" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>