<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_ArmInit" Id="{2f1b91d8-ebd5-4b63-92d8-450fe3a94973}" SpecialFunc="None">
    <Declaration><![CDATA[// Brief: Master Arm Initialization
FUNCTION_BLOCK PUBLIC FB_ArmInit EXTENDS FB_MasterArmCtrlBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="driverCtrl" Id="{3c0d3c75-d2c1-4fba-8adc-8dcd06c0025a}">
      <Declaration><![CDATA[METHOD PUBLIC driverCtrl : BOOL
VAR_IN_OUT CONSTANT
	i_masterArm :FB_MasterArm;
END_VAR
VAR
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[m_jntEnableFlag :=g_onesVec7i;

// controller finished if both arm is all enabled
m_isFinished := i_masterArm.isEnabled(m_jntEnableFlag) ;



]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_ArmInit">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_ArmInit.driverCtrl">
      <LineId Id="31" Count="0" />
      <LineId Id="37" Count="0" />
      <LineId Id="30" Count="0" />
      <LineId Id="28" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="15" Count="0" />
      <LineId Id="14" Count="0" />
      <LineId Id="13" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>